#!/bin/bash
echo "Running test"

INPUT_DEBUG="True" \
INPUT_IMAGES_MAX_WIDTH="1500" \
INPUT_IMAGES_QUALITY="90" \
INPUT_IMAGES_FORMATS="jpg, jpge, png" \
INPUT_IMAGES_DIRECTORIES="tests/path_1, tests/path_2" \
INPUT_IMAGES_PREFIX="prefix" \
INPUT_IMAGES_SUFFIX="suffix" \
python3 main.py